# Generated by Django 4.2.5 on 2023-09-29 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='room_ID')),
                ('room_name', models.CharField(max_length=25, verbose_name='room_name')),
                ('room_created_on', models.DateTimeField(auto_now_add=True, verbose_name='room_created_on')),
                ('room_slug', models.SlugField(verbose_name='room_slug')),
                ('room_admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='room_admin')),
            ],
        ),
    ]
